server:
  port: 9000
  maxHttpHeadSize: 65536

spring:
  application:
    name: weixin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 500MB

logging:
  config: classpath:log.xml
  level:
    root: debug